name: Push Source Files to Applanga
on:
  push:
    branches:
      - main
    paths:
      - app.js
  workflow_dispatch:
    inputs:
      push_targets:
        type: boolean
        description: Push translation files. If set translation files will be pushed instead of source files
        default: false
        required: false
      branch_id:
        description: Branch ID
        required: false
        type: string
jobs:
  push-sources-for-translation:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare Applanga API Configuration
        id: api_config
        env:
          ACCESS_TOKEN: ${{ secrets.APPLANGA_ACCESS_TOKEN }}
          BRANCH_ID_INPUT: '${{ github.event.inputs.branch_id }}'
          APPLANGA_API_HOST: ${{ secrets.APPLANGA_API_HOST }}
        run: "|\n\t\t\t\t\t\t\t\t\t# Prepare API host from secret or fallback\n\t\t\t\t\t\t\t\t\t# Set API host from secret or use fallback, then remove any trailing slash\n\t\t\t\t\t\t\t\t\tRAW_HOST=\"${APPLANGA_API_HOST_SECRET:-'https://api.applanga.com'}\"\n\t\t\t\t\t\t\t\t\tCLEANED_HOST=\"${RAW_HOST%/}\"\n\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t# Extract mobile app ID from access token\n\t\t\t\t\t\t\t\t\tMOBILE_APP_ID=$(echo \"$ACCESS_TOKEN\" | cut -d'!' -f1)\n\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t# Prepare branch ID parameter string if an ID is provided\n\t\t\t\t\t\t\t\t\tBRANCH_PARAM=\"\"\n\t\t\t\t\t\t\t\t\tif [ -n \"$BRANCH_ID_INPUT\" ]; then\n\t\t\t\t\t\t\t\t\t\tBRANCH_PARAM=\"&branch=$BRANCH_ID_INPUT\"\n\t\t\t\t\t\t\t\t\tfi\n\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t# Set all values as outputs for downstream steps\n\t\t\t\t\t\t\t\t\techo \"mobile_app_id=${MOBILE_APP_ID}\" >> $GITHUB_OUTPUT\n\t\t\t\t\t\t\t\t\techo \"branch_param=${BRANCH_PARAM}\" >> $GITHUB_OUTPUT\n\t\t\t\t\t\t\t\t\techo \"api_host=${CLEANED_HOST}\" >> $GITHUB_OUTPUT\n\t\t\t\t\t\t\t\t"
      - name: Notify workflow started
        run: |-
          curl -X POST "${{ steps.api_config.outputs.api_host }}/v1/api/workflow-start?app=${{ steps.api_config.outputs.mobile_app_id }}${{ steps.api_config.outputs.branch_param }}" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.APPLANGA_ACCESS_TOKEN }}" \
            -d '{
            "workflowType": "push"
            }' || echo "Failed to notify workflow start, continuing anyway"
      - uses: actions/checkout@v3
        with:
          path: checkout
      - uses: applanga/setup-applanga-cli@v1.0.3
        with:
          version: 1.0.*
      - name: Push Sources to Applanga
        if: '${{ inputs.push_targets != true }}'
        env:
          APPLANGA_ACCESS_TOKEN: '${{ secrets.APPLANGA_ACCESS_TOKEN }}'
          APPLANGA_API_HOST: '${{ steps.api_config.outputs.api_host }}'
        run: applanga push --force
        working-directory: checkout
      - name: Push Translation Files to Applanga
        if: '${{ inputs.push_targets == true }}'
        env:
          APPLANGA_ACCESS_TOKEN: '${{ secrets.APPLANGA_ACCESS_TOKEN }}'
        run: applanga pushtarget --force
        working-directory: checkout
      - name: Notify workflow success
        if: success()
        run: |-
          curl -X POST "${{ steps.api_config.outputs.api_host }}/v1/api/workflow-start?app=${{ steps.api_config.outputs.mobile_app_id }}${{ steps.api_config.outputs.branch_param }}" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.APPLANGA_ACCESS_TOKEN }}" \
            -d '{
            "workflowType": "push",
              "status": "success"
            }' || echo "Failed to notify workflow success"
      - name: Notify workflow failure
        if: failure()
        run: |-
          curl -X POST "${{ steps.api_config.outputs.api_host }}/v1/api/workflow-start?app=${{ steps.api_config.outputs.mobile_app_id }}${{ steps.api_config.outputs.branch_param }}" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.APPLANGA_ACCESS_TOKEN }}" \
            -d '{
            "workflowType": "push",
              "status": "failed"
            }' || echo "Failed to notify workflow failure"
